# Домашнее задание 2 (5 баллов).

Все задания ниже имеют равный вес (5/16).

In [262]:
import pandas as pd

#### Описание данных

В папке Dat (https://github.com/hse-ds/iad-intro-ds/blob/master/2023/homeworks/Data.zip) находится информация о студентах. Всего 10 групп студентов. Файлы делятся на две категории:
    * Students_info_i - информация о студентах из группы i
    * Students_marks_i - оценки студентов из группы i за экзамены

### Одно из важных достоинств pandas $-$ это удобные методы реляционного взаимодействия с данными, аналогичные, например, возможностям SQL для слияния и конкатенации таблиц: merge, join, concat. Наличие готовых методов позволяет не реализовывать самостоятельно поэлементную обработку данных и оперировать сразу целыми таблицами данных.

Подробно об этих методах посмотрите тут: https://www.kaggle.com/residentmario/renaming-and-combining#Combining

#### Задание 1. Соберите всю информацию о студентах в одну таблицу df. В получившейся таблице должна быть информация и оценки всех студентов из всех групп. Напечатайте несколько строк таблицы для демонстрации результата.¶

In [263]:
info = pd.concat([pd.read_csv(f'Students_info_{i}.csv') for i in range(10)])
marks = pd.concat([pd.read_csv(f'Students_marks_{i}.csv') for i in range(10)])
data = info.merge(marks)

data.head(1000)

,index,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,1,female,group C,some college,standard,completed,group1,69,90,88
2,2,female,group B,master's degree,standard,none,group1,90,95,93
3,3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...,...
995,995,female,group E,master's degree,standard,completed,group10,88,99,95
996,996,male,group C,high school,free/reduced,none,group10,62,55,55
997,997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,998,female,group D,some college,standard,completed,group10,68,78,77
999,999,female,group D,some college,free/reduced,none,group10,77,86,86

#### Задание 2. Удалите столбец index у полученной таблицы. Напечатайте первые 10 строк таблицы.

In [264]:
my_table = data.drop("index", axis = 1)
my_table.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
5,female,group B,associate's degree,standard,none,group1,71,83,78
6,female,group B,some college,standard,completed,group1,88,95,92
7,male,group B,some college,free/reduced,none,group1,40,43,39
8,male,group D,high school,free/reduced,completed,group1,64,64,67
9,female,group B,high school,free/reduced,none,group1,38,60,50

#### Задание 3. Выведите на экран размеры полученной таблицы

In [265]:
my_table.shape

(1000, 9)

#### Задание 4. Выведите на экран статистические характеристики числовых столбцов таблицы (минимум, максимум, среднее значение, стандартное отклонение)

In [266]:
my_table.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

#### Задание 5. Проверьте, есть ли в таблице пропущенные значения

In [267]:
my_table.isnull().any().any()

False

#### Задание 6. Выведите на экран средние баллы студентов по каждому предмету (math, reading, writing)

In [268]:
# по каждому
my_table[['math score', 'reading score', 'writing score']].mean()

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

**Задание 7. Как зависят оценки от того, проходил ли студент курс для подготовки к сдаче экзамена (test preparation course)? Выведите на экран для каждого предмета в отдельности средний балл студентов, проходивших курс для подготовки к экзамену и не проходивших курс.**

In [269]:
my_table.groupby('test preparation course').mean(numeric_only=True)

                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

---
Вывод

Оценки по каждому предмету у студентов, проходивших курс для подготовки к экзамену,заметно выше, чем у не проходивших курс

---

In [271]:
completed_course = my_table[my_table['test preparation course'] == 'completed']
completed_course_score = completed_course[['math score', 'reading score', 'writing score']]
completed_course_average_score = completed_course_score.mean()

no_course = my_table[my_table['test preparation course'] != 'completed']
no_course_score = no_course[['math score', 'reading score', 'writing score']]
no_course_average_score = no_course_score.mean()

print('completed course')
for val in completed_course_average_score.values:
  print(val)

print('\ndidn\'t complete course')
for val in no_course_average_score:
    print(val)

completed course
69.69553072625699
73.89385474860335
74.41899441340782

didn't complete course
64.0778816199377
66.53426791277259
64.50467289719626

**Задание 8. Выведите на экран все различные значения из столбца lunch.**

In [272]:
print(my_table['lunch'].unique())

['standard' 'free/reduced']

In [273]:
my_table['lunch'].drop_duplicates()

0        standard
3    free/reduced
Name: lunch, dtype: object

**Задание 9. Переименуйте колонку "parental level of education" в "education", а "test preparation course" в "test preparation" с помощью метода pandas rename**
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.rename.html

In [274]:
my_table = my_table.rename(columns = {"parental level of education" : "education", "test preparation course" : "test preparation"})
my_table

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,group1,72,72,74
1,female,group C,some college,standard,completed,group1,69,90,88
2,female,group B,master's degree,standard,none,group1,90,95,93
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44
4,male,group C,some college,standard,none,group1,76,78,75
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95
996,male,group C,high school,free/reduced,none,group10,62,55,55
997,female,group C,high school,free/reduced,completed,group10,59,71,65
998,female,group D,some college,standard,completed,group10,68,78,77
999,female,group D,some college,free/reduced,none,group10,77,86,86

**Зафиксируем минимальный балл для сдачи экзамена**

In [275]:
passmark = 50

**Задание 10. Ответьте на вопросы:**
    * Какая доля студентов сдала экзамен по математике (passmark >= 50)?
    * Какая доля студентов, проходивших курс подготовки к экзамену, сдала экзамен по математике?
    * Какая доля женщин, не проходивших курс подготовки к экзамену, не сдала экзамен по математике?

In [276]:
passed = my_table[my_table['math score'] >= passmark].count()[0]
total = my_table.count()[0]
print(f"Passed exam: {passed / total}")

Passed exam: 0.865

In [278]:
completed_course_passed = my_table[(my_table['test preparation'] == 'completed') & (my_table['math score'] >= passmark)].count()[0]
total = my_table.count()[0]
print(f"Passed exam with course: {completed_course_passed / total}")

Passed exam with course: 0.33

In [280]:
female_relevant = my_table[(my_table['gender'] == 'female') & (my_table['test preparation'] == 'none') & (my_table['math score'] < passmark)].count()[0]
female_total = my_table[(my_table['gender'] == 'female')].count()[0]
print(f"Females not passed exam no course: {female_relevant / female_total}")

Females not passed exam no course: 0.13513513513513514

**Задание 11. С помощью groupby выполните задания ниже. Также выведите время выполнения каждого из заданий.**
    * Для каждой этнической группы выведите средний балл за экзамен по чтению
    * Для каждого уровня образования выведите минимальный балл за экзамен по письму

In [281]:
import time

In [282]:
time_start = time.time()
reading_scores_by_ethnicity = my_table.groupby('race/ethnicity')['reading score'].mean()
print(reading_scores_by_ethnicity)
print(f"\nTime elapsed: {time.time() - time_start}")

race/ethnicity
group A    64.674157
group B    67.352632
group C    69.103448
group D    70.030534
group E    73.028571
Name: reading score, dtype: float64

Time elapsed: 0.003870725631713867

In [283]:
time_start = time.time()
writing_scores_by_education = my_table.groupby('education')['writing score'].min()
print(writing_scores_by_education)
print(f"\nTime elapsed: {time.time() - time_start}")

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10
Name: writing score, dtype: int64

Time elapsed: 0.002925872802734375

**Задание 12. Выполните задание 11 с помощью циклов. Сравните время выполнения.**

In [284]:
time_start = time.time()

print("ethnicity")
for i in my_table['race/ethnicity'].sort_values().unique():
  reading_scores_by_ethnicity = my_table[my_table['race/ethnicity'] == i]['reading score'].mean()
  print(f"{i}    {reading_scores_by_ethnicity}")

print(f"\nTime elapsed: {time.time() - time_start}")

ethnicity
group A    64.67415730337079
group B    67.35263157894737
group C    69.10344827586206
group D    70.03053435114504
group E    73.02857142857142

Time elapsed: 0.014177083969116211

In [285]:
time_start = time.time()

print("education")
for i in my_table['education'].sort_values().unique():
  education = i
  while len(education) != 22: education += ' '
  writing_score_by_education = my_table[my_table['education'] == i]['writing score'].min()
  print(education + f"{writing_score_by_education}")

print(f"\nTime elapsed: {time.time() - time_start}")

education
associate's degree    35
bachelor's degree     38
high school           15
master's degree       46
some college          19
some high school      10

Time elapsed: 0.009131193161010742

**Задание 13. Выведите на экран средние баллы студентов по каждому предмету в зависимости от пола и уровня образования. То есть должно получиться количество групп, равных 2 * (число уровней образования), и для каждой такой группы выыведите средний балл по каждому из предметов.**

Это можно сделать с помощью сводных таблиц (pivot_table):

https://www.kaggle.com/kamilpolak/tutorial-how-to-use-pivot-table-in-pandas

In [287]:
# dat = pd.pivot_table(data=df, index=['parental level of education'], values=['math score', 'reading score', 'writing score'])
# dat
# mid = df[df['high school'] == 'high school']

def main(name):
  if name == 'some college' or name == 'high school' or name == 'some high school':
    return 'middle education (some college, high school, some high school)'
  return 'high education (bachelor,  master, associate degrees)'


my_table['level of education'] = my_table[('education')].apply(main)

pivot_table = my_table.pivot_table(index=['level of education', 'gender'], aggfunc='mean')
pivot_table

<ipython-input-287-71b202894bf7>:13: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  pivot_table = my_table.pivot_table(index=['level of education', 'gender'], aggfunc='mean')

                                                           math score  \
level of education                                 gender
high education (bachelor,  master, associate de... female   66.367442
                                                   male     71.217391
middle education (some college, high school, so... female   61.693069
                                                   male     67.191275

                                                           reading score  \
level of education                                 gender
high education (bachelor,  master, associate de... female      75.497674
                                                   male        68.342391
middle education (some college, high school, so... female      70.557756
                                                   male        63.701342

                                                           writing score
level of education                                 gender
high education (bachelor,  master, associate de... female      75.893023
                                                   male        66.978261
middle education (some college, high school, so... female      70.036304
                                                   male        61.046980

#### Задание 14. Сколько студентов успешно сдали экзамен по математике?

Создайте новый столбец в таблице df под названием Math_PassStatus и запишите в него F, если студент не сдал экзамен по математике (балл за экзамен < passmark), и P иначе.

Посчитайте количество студентов, сдавших и не сдавших экзамен по математике.

Сделайте аналогичные шаги для экзаменов по чтению и письму.

In [288]:
def pass_status(mark):
  if mark >= passmark:
    return 'P'
  return 'F'

my_table['Math PassStatus'] = my_table['math score'].apply(pass_status)
count = my_table[my_table['Math PassStatus'] == 'F'].count()
count

gender                135
race/ethnicity        135
education             135
lunch                 135
test preparation      135
group                 135
math score            135
reading score         135
writing score         135
level of education    135
Math PassStatus       135
dtype: int64

#### Задание 15. Сколько студентов успешно сдали все экзамены?

Создайте столбец OverAll_PassStatus и запишите в него для каждого студента 'F', если студент не сдал хотя бы один из трех экзаменов, а иначе 'P'.

Посчитайте количество студентов, которые сдали все экзамены.

In [289]:
def pass_status(mark):
  if mark >= passmark:
    return 1
  return 0
def name(num):
  if num == 3:
    return 'P'
  return 'F'
my_table['Math PassStatus'] = my_table['math score'].apply(pass_status)
my_table['Reading PassStatus'] = my_table['reading score'].apply(pass_status)
my_table['Writing PassStatus'] = my_table['writing score'].apply(pass_status)
my_table['Summ'] = my_table['Math PassStatus']+ my_table['Reading PassStatus']+ my_table['Writing PassStatus']
my_table['OverAll PassStatus'] = my_table['Summ'].apply(name)
count = my_table[my_table['Summ'] == 3].count()
print(count)
my_table.drop(['Math PassStatus', 'Reading PassStatus', 'Writing PassStatus', 'Summ'], axis= 1)

gender                812
race/ethnicity        812
education             812
lunch                 812
test preparation      812
group                 812
math score            812
reading score         812
writing score         812
level of education    812
Math PassStatus       812
Reading PassStatus    812
Writing PassStatus    812
Summ                  812
OverAll PassStatus    812
dtype: int64

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,level of education,OverAll PassStatus
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,"high education (bachelor, master, associate d...",P
1,female,group C,some college,standard,completed,group1,69,90,88,"middle education (some college, high school, s...",P
2,female,group B,master's degree,standard,none,group1,90,95,93,"high education (bachelor, master, associate d...",P
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,"high education (bachelor, master, associate d...",F
4,male,group C,some college,standard,none,group1,76,78,75,"middle education (some college, high school, s...",P
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95,"high education (bachelor, master, associate d...",P
996,male,group C,high school,free/reduced,none,group10,62,55,55,"middle education (some college, high school, s...",P
997,female,group C,high school,free/reduced,completed,group10,59,71,65,"middle education (some college, high school, s...",P
998,female,group D,some college,standard,completed,group10,68,78,77,"middle education (some college, high school, s...",P
999,female,group D,some college,free/reduced,none,group10,77,86,86,"middle education (some college, high school, s...",P

#### Задание 16. Переведем баллы в оценки

### Система перевода баллов в оценки
####    больше 90 = A
####      80-90 = B
####      70-80 = C
####      60-70 = D
####      50-60 = E
####    меньше 50 = F (Fail)

Создайте вспомогательную функцию, которая будет по среднему баллу за три экзамена выставлять оценку студенту по данным выше критериям.

Создайте столбец Grade и запишите в него оценку каждого студента.

Выведите количество студентов, получивших каждую из оценок.

**В случае, если средний балл попадает на границу между оценками (т.е. равен ровно 60, 70 или 80 баллов), вы можете интерпретировать условие на своё усмотрение (т.е. можете поставить за 60 баллов оценку D, а можете - E).**

In [291]:
def GetGrade(average_mark):
  if average_mark >= 90:
    return 'A'
  elif 80 <= average_mark < 90:
    return 'B'
  elif 70 <= average_mark < 80:
    return 'C'
  elif 60 <= average_mark < 70:
    return 'C'
  elif 50 <= average_mark < 60:
    return 'C'
  return 'F'

my_table['Grade'] = ((my_table['math score'] + my_table['reading score'] + my_table['writing score']) / 3).apply(GetGrade)
my_table

,gender,race/ethnicity,education,lunch,test preparation,group,math score,reading score,writing score,level of education,Math PassStatus,Reading PassStatus,Writing PassStatus,Summ,OverAll PassStatus,Grade
0,female,group B,bachelor's degree,standard,none,group1,72,72,74,"high education (bachelor, master, associate d...",1,1,1,3,P,C
1,female,group C,some college,standard,completed,group1,69,90,88,"middle education (some college, high school, s...",1,1,1,3,P,B
2,female,group B,master's degree,standard,none,group1,90,95,93,"high education (bachelor, master, associate d...",1,1,1,3,P,A
3,male,group A,associate's degree,free/reduced,none,group1,47,57,44,"high education (bachelor, master, associate d...",0,1,0,1,F,F
4,male,group C,some college,standard,none,group1,76,78,75,"middle education (some college, high school, s...",1,1,1,3,P,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,group10,88,99,95,"high education (bachelor, master, associate d...",1,1,1,3,P,A
996,male,group C,high school,free/reduced,none,group10,62,55,55,"middle education (some college, high school, s...",1,1,1,3,P,C
997,female,group C,high school,free/reduced,completed,group10,59,71,65,"middle education (some college, high school, s...",1,1,1,3,P,C
998,female,group D,some college,standard,completed,group10,68,78,77,"middle education (some college, high school, s...",1,1,1,3,P,C
999,female,group D,some college,free/reduced,none,group10,77,86,86,"middle education (some college, high school, s...",1,1,1,3,P,B